### ISSUE TITLE
请问如何安装使用？

### ISSUE THREAD

**Issue by nigo81** [Eliot00/mp-org#6]
作者您好，我平时也使用emacs的org写文档，也会发公众号文章。请问可以介绍下如何安装使用这个插件吗？感谢！

**Comment by Eliot00** [comment]
你是什么操作系统呢？在[这里](https://github.com/Eliot00/mp-org/releases)下载对应系统的包，例如是Windows就下载
`mp-org_0.2.0_x64-setup.exe `

**Comment by Eliot00** [comment]
这是个webview应用，没有做成emacs插件，现在功能还很少，欢迎试用后提issue

**Comment by nigo81** [comment]
> 这是个webview应用，没有做成emacs插件，现在功能还很少，欢迎试用后提issue

非常感谢，我下载了linux版本试了可以！之前我是在emacs转成markdown格式，然后再使用mdnice转成带样式的公众号文章。

![image](https://github.com/Eliot00/mp-org/assets/38601513/db80e984-b353-41f6-a156-09fbc703f70e)
我看对于加粗符号有没有正确解析的。希望作者继续完善下去，对于emacs用户来说很有用。我之前找类似的工具没有找到。

看后续是否可以考虑解决以下问题：

1. 可以多样主题或者可以复制mdnice上面的主题样式过来或者允许怎么自定义。（不太懂前端）。
2. 如果解决图片复制的问题。在org中图片都是本地链接，转换后没法粘贴到公众号上。看能不能粘贴图片，或者一键上传图床后复制粘贴。

再次感谢作者！持续关注。

**Comment by Eliot00** [comment]
#7 
#8

**Comment by Eliot00** [comment]
加粗样式的话，org格式必须在星号前后有空格

**Comment by Eliot00** [comment]
<img width="980" alt="截屏2024-03-14 17 15 26" src="https://github.com/Eliot00/mp-org/assets/18375468/e59878d0-b65c-4a5c-9869-1c7e3069c57f">

**Comment by Eliot00** [comment]
自定义样式和上传图片预计这周搞定

**Comment by nigo81** [comment]
> 自定义样式和上传图片预计这周搞定

非常感谢，org使用的太小众了，估计也就是自己使用的才有动力维护开发。不着急哈，您慢慢来。因为org中的图片链接我是用的相对路径，如`[[file:../orgimages/2024-02-03_23-25-34_screenshot.png]]`不知道这种能够实现上传不。org中我是使用`org-download-clipboard`和`org-download-image`将剪切板和其它路径图片自动保存到指定目录`~/orgimages`上的。

**Comment by Eliot00** [comment]
commit afbfd45436b88fb29b02f0e1021802d3e3c12ce1 解决了中文空格的问题
添加了一个按钮，作用是在前后没有空格的标记前添加零宽空格

点击前：

```org
你好*世界*
```

点击后：

```org
你好\u200B*世界*\u200B
```

**Comment by yibie** [comment]
Mac 下安装包会出现安装包损坏的提示。安装版本 0.7，系统版本号 macOS 15.3。


![Image](https://github.com/user-attachments/assets/5ca8c830-049d-4944-b7f0-4385a79213b8)
